### ISSUE TITLE
Unable to communicate with NsDepCop service

### ISSUE THREAD

**Issue by TC-M** [realvizu/NsDepCop#43]
I am installing NsDepCop for the first time. NuGet package v1.8.0 installed without issue and created config.nsdepcop. Also, the extensions NsDepCop VS2017 and NsDepCop Config XML Schema Support installed without issue. However, every time I build my project, I get the "Unable to communicate with NsDepCop service" exception. I have read the Troubleshooting page and https://github.com/realvizu/NsDepCop/issues/29, in which a similar issue was reported. I know that you've diagnosed the cause of this exception as a timing issue -- the client doesn't wait long enough for the server to spin up. However, I've increased the wait times drastically and continue to get the error every time.

AnalyzerServiceCallRetryTimeSpans="1000,10000,100000"

Do you have any suggestions about how I might further debug this issue?

-TC

**Comment by realvizu** [comment]
Is there a full exception string (with full exception message and call stack) in the build output? If so please post it.

**Comment by TC-M** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception during NsDepCopTask execution: System.Exception: Unable to communicate with NsDepCop service. All retries failed. ---> System.Runtime.Remoting.RemotingException: Failed to connect to an IPC Port: The system cannot find the file specified.
 

Server stack trace: 
   at System.Runtime.Remoting.Channels.Ipc.IpcPort.Connect(String portName, Boolean secure, TokenImpersonationLevel impersonationLevel, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.ConnectionCache.GetConnection(String portName, Boolean secure, TokenImpersonationLevel level, Int32 timeout)
   at System.Runtime.Remoting.Channels.Ipc.IpcClientTransportSink.ProcessMessage(IMessage msg, ITransportHeaders requestHeaders, Stream requestStream, ITransportHeaders& responseHeaders, Stream& responseStream)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Codartis.NsDepCop.Core.Interface.Analysis.Remote.IRemoteDependencyAnalyzer.AnalyzeProject(IAnalyzerConfig config, String[] sourcePaths, String[] referencedAssemblyPaths)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.InvokeRemoteAnalyzer(IEnumerable`1 sourceFilePaths, IEnumerable`1 referencedAssemblyPaths)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.<>c__DisplayClass6_0.<GetIllegalTypeDependencies>b__0()
   at Codartis.NsDepCop.Core.Util.RetryHelper.Retry[TResult](Func`1 func, Int32 maxRetryCount, BeforeRetryCallback beforeRetryAction)
   --- End of inner exception stack trace ---
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.OnAllRetriesFailed(Exception exception)
   at OneOf.OneOf`2.Match[TResult](Func`2 f0, Func`2 f1)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.GetIllegalTypeDependencies(IEnumerable`1 sourceFilePaths, IEnumerable`1 referencedAssemblyPaths)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.<>c__DisplayClass3_0.<AnalyzeProject>b__0()
   at Codartis.NsDepCop.Core.Implementation.Analysis.DependencyAnalyzerBase.<PerformAnalysis>d__9.MoveNext()
   at Codartis.NsDepCop.Core.Implementation.Analysis.DependencyAnalyzerBase.<AnalyzeCore>d__8.MoveNext()
   at Codartis.NsDepCop.MsBuildTask.NsDepCopTask.Execute()	AIM_LP_Engine_CS

**Comment by TC-M** [comment]
I followed all the steps.
- NsDepCop.ServiceHost.exe and many DLLs are in \<solution folder>\packages\NsDepCop.1.8.0\tools.
- NsDepCop.ServiceHost.exe runs from the command window without throwing an exception.
- pipelist64.exe confirms that NsDepCop-1.8.0.204 is listening.
- When I build the project, I get an exception different from before. The error message says "Unable to find assembly 'NsDepCop.Core...'", but I don't know why that is the case; NsDepCop.Core.dll is in \<solution folder>\packages\NsDepCop.1.8.0\tools, and the version numbers match.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Exception during NsDepCopTask execution: System.Exception: Unable to communicate with NsDepCop service. All retries failed. ---> System.Runtime.Serialization.SerializationException: Unable to find assembly 'NsDepCop.Core, Version=1.8.0.204, Culture=neutral, PublicKeyToken=null'.

Server stack trace: 
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.BinaryConverter.TypeFromInfo(BinaryTypeEnum binaryTypeEnum, Object typeInformation, ObjectReader objectReader, BinaryAssemblyInfo assemblyInfo, InternalPrimitiveTypeE& primitiveTypeEnum, String& typeString, Type& type, Boolean& isVariant)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Remoting.Channels.CoreChannel.DeserializeBinaryResponseMessage(Stream inputStream, IMethodCallMessage reqMsg, Boolean bStrictBinding)
   at System.Runtime.Remoting.Channels.BinaryClientFormatterSink.SyncProcessMessage(IMessage msg)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Codartis.NsDepCop.Core.Interface.Analysis.Remote.IRemoteDependencyAnalyzer.AnalyzeProject(IAnalyzerConfig config, String[] sourcePaths, String[] referencedAssemblyPaths)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.InvokeRemoteAnalyzer(IEnumerable`1 sourceFilePaths, IEnumerable`1 referencedAssemblyPaths)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.<>c__DisplayClass6_0.<GetIllegalTypeDependencies>b__0()
   at Codartis.NsDepCop.Core.Util.RetryHelper.Retry[TResult](Func`1 func, Int32 maxRetryCount, BeforeRetryCallback beforeRetryAction)
   --- End of inner exception stack trace ---
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.OnAllRetriesFailed(Exception exception)
   at OneOf.OneOf`2.Match[TResult](Func`2 f0, Func`2 f1)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.GetIllegalTypeDependencies(IEnumerable`1 sourceFilePaths, IEnumerable`1 referencedAssemblyPaths)
   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.<>c__DisplayClass3_0.<AnalyzeProject>b__0()
   at Codartis.NsDepCop.Core.Implementation.Analysis.DependencyAnalyzerBase.<PerformAnalysis>d__9.MoveNext()
   at Codartis.NsDepCop.Core.Implementation.Analysis.DependencyAnalyzerBase.<AnalyzeCore>d__8.MoveNext()
   at Codartis.NsDepCop.MsBuildTask.NsDepCopTask.Execute()	AIM_LP_Engine_CS			
```

**Comment by realvizu** [comment]
I have no clue what is happening.
Can you post an example project here on github so I can try to run it on my machine and get a repro?

**Comment by TC-M** [comment]
I have new findings to report.

I tried to create a sample project to send you as a demonstration of the error, but I was not able to reproduce the error in a new project -- NsDepCop worked perfectly. That suggests there is something unusual about my work project which causes the error. However, I can't figure out what that is.

Here is something else interesting: If NsDepCop starts successfully, it continues working for all projects, but if it starts with a failure, it continues to fail for all projects. Suppose I open two Visual Studio windows, one with my work solution and one with my sample solution. If the first project I build is in the sample solution, NsDepCop will succeed and continue to work when I build projects in my work solution. If the first project I build is in my work solution, then NsDepCop will fail and continue to fail when I build projects in my sample solution.

I'll let you know if I learn anything else.

**Comment by realvizu** [comment]
Please try one more thing.
Set MsBuild's log verbosity to **Detailed** in `Visual Studio / Tools / Options / Projects and Solutions / Build and Run / MSBuild project build output verbosity.`
Then you can find NsDepCop's trace messages in the Output window by searching for the string: `[NsDepCop]`
Try to generate a log for the failing and for the succeeding cases too. Maybe we can figure out something from any differences we may find in them.

**Comment by TC-M** [comment]
It looks like the problem is related to spaces in the solution folder path. Here is part of the detailed error log:
```
2>  [NsDepCop] Trying to activate analyzer service (attempt #1).
2>  [NsDepCop] Starting C:\Users\TC\Documents\AIM%20Code\trunk\packages\NsDepCop.1.8.0\tools\NsDepCop.ServiceHost.exe with parameter 11320
2>  [NsDepCop]   Working folder is C:\Users\TC\Documents\AIM%20Code\trunk\packages\NsDepCop.1.8.0\tools
2>  [NsDepCop] AnalyzerServiceActivator.CreateServer failed: System.ComponentModel.Win32Exception (0x80004005): The directory name is invalid
```
When I changed the folder name from "AIM Code" to "AIM_Code", the errors ceased.

**Comment by realvizu** [comment]
Wow, thanks a lot for taking the time to figure it out!
I'll fix it as soon as I'll have some time.

**Comment by realvizu** [comment]
Fixed in v1.8.1: https://www.nuget.org/packages/NsDepCop/1.8.1
Please let me know whether that fixed the issue!

**Comment by TC-M** [comment]
I just got back to looking at this again today. The problem persists.
Specifically, I continue to get "Unable to communicate with NsDepCop
service" whenever I build a project whose solution path has a space.
I've pasted the relevant part of the log below. This time, all the paths
in the log seem to be correct. However, I think this is still a
space-in-the-path issue because when I move the solution to a no-space
path and build, the error goes away.

-TC

    2>  [NsDepCop] Calling analyzer service.
    2>  [NsDepCop] Unable to communicate with NsDepCop service.
    Exception: Unable to find assembly 'NsDepCop.Core,
    Version=1.8.1.214, Culture=neutral, PublicKeyToken=null'.
    2>  [NsDepCop] Trying to activate analyzer service (attempt #1).
    2>  [NsDepCop] Starting C:\Users\TC\Documents\AIM
    Code\trunk\packages\NsDepCop.1.8.1\tools\NsDepCop.ServiceHost.exe
    with parameter 11904
    2>  [NsDepCop]   Working folder is C:\Users\TC\Documents\AIM
    Code\trunk\packages\NsDepCop.1.8.1\tools
    2>  [NsDepCop] Retrying service call after: 00:00:00.1000000.
    2>  [NsDepCop] Calling analyzer service.
    2>  [NsDepCop] Unable to communicate with NsDepCop service.
    Exception: Unable to find assembly 'NsDepCop.Core,
    Version=1.8.1.214, Culture=neutral, PublicKeyToken=null'.
    2>  [NsDepCop] Trying to activate analyzer service (attempt #2).

**Comment by realvizu** [comment]
You're right, there was another similar bug in the assembly resolution folder name handling.
Fixed in: https://www.nuget.org/packages/NsDepCop/1.8.2-beta1

Now I'm a bit more cautious and publish the fix as beta version and will publish a release when you confirm that it actually fixed the issue. Please let me know!

**Comment by laedit** [comment]
I had the same issue with a space in the solution path and I can confirm that the beta indeed fixes it.

**Comment by realvizu** [comment]
Thanks for the feedback.
The fix is released: https://www.nuget.org/packages/NsDepCop/1.8.2

**Comment by JojoShow** [comment]
Hello,

We have reproduced this issue with version 1.10.1.
We had a ".NET Framework" project that was working with an old version of NsDepCop (not a NuGet package)
We have split our big project in several logical parts and some of thes parts have been changed to ".NET Standard" 
When creating the new ".NET Standard" projects, we have included NsDepCop as NuGet package and when we run a build on a **MAC** server, we have the message "Unable to communicate with NsDepCop service"

_NOTE: there's no space in folder names on our build server_

Here is the full error log:

 ```
"/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj" (default target) (38:3) ->

(NsDepCop_Analyze target) -> 
MSBUILD : error : Exception during NsDepCopTask execution: System.Exception: Unable to communicate with NsDepCop service. All retries failed. ---> System.Runtime.Remoting.RemotingException: Connection refused [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error : Server stack trace:  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Mono.Remoting.Channels.Unix.HostConnectionPool.CreateConnection () [0x00029] in <1d40e9c569b440bd94b2b11855d66b47>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Mono.Remoting.Channels.Unix.HostConnectionPool.GetConnection () [0x0009d] in <1d40e9c569b440bd94b2b11855d66b47>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Mono.Remoting.Channels.Unix.UnixConnectionPool.GetConnection (System.String path) [0x00043] in <1d40e9c569b440bd94b2b11855d66b47>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Mono.Remoting.Channels.Unix.UnixClientTransportSink.ProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg, System.Runtime.Remoting.Channels.ITransportHeaders requestHeaders, System.IO.Stream requestStream, System.Runtime.Remoting.Channels.ITransportHeaders& responseHeaders, System.IO.Stream& responseStream) [0x00022] in <1d40e9c569b440bd94b2b11855d66b47>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Mono.Remoting.Channels.Unix.UnixBinaryClientFormatterSink.SyncProcessMessage (System.Runtime.Remoting.Messaging.IMessage msg) [0x00066] in <1d40e9c569b440bd94b2b11855d66b47>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error : Exception rethrown at [0]:  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (System.Runtime.Remoting.Proxies.RealProxy rp, System.Runtime.Remoting.Messaging.IMessage msg, System.Exception& exc, System.Object[]& out_args) [0x0014d] in <55adae4546cd485ba70e2948332ebe8c>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at (wrapper managed-to-native) System.Object.__icall_wrapper_mono_remoting_wrapper(intptr,intptr) [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at (wrapper remoting-invoke) Codartis.NsDepCop.Core.Interface.Analysis.Remote.IRemoteDependencyAnalyzer.AnalyzeProject(Codartis.NsDepCop.Core.Interface.Config.IAnalyzerConfig,string[],string[]) [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.InvokeRemoteAnalyzer (System.Collections.Generic.IEnumerable`1[T] sourceFilePaths, System.Collections.Generic.IEnumerable`1[T] referencedAssemblyPaths) [0x00047] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient+<>c__DisplayClass6_0.<GetIllegalTypeDependencies>b__0 () [0x00000] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Util.RetryHelper.Retry[TResult] (System.Func`1[TResult] func, System.Int32 maxRetryCount, Codartis.NsDepCop.Core.Util.BeforeRetryCallback beforeRetryAction) [0x00030] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :    --- End of inner exception stack trace --- [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.OnAllRetriesFailed (System.Exception exception) [0x0000b] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at OneOf.OneOf`2[T0,T1].Match[TResult] (System.Func`2[T,TResult] f0, System.Func`2[T,TResult] f1) [0x00024] in <16bc1641e0ed40cd8aee20d0e1ccaa46>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient.GetIllegalTypeDependencies (System.Collections.Generic.IEnumerable`1[T] sourceFilePaths, System.Collections.Generic.IEnumerable`1[T] referencedAssemblyPaths) [0x0005e] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Implementation.Analysis.Remote.RemoteDependencyAnalyzerClient+<>c__DisplayClass3_0.<AnalyzeProject>b__0 () [0x00000] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Implementation.Analysis.DependencyAnalyzerBase+<PerformAnalysis>d__9.MoveNext () [0x00095] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.Core.Implementation.Analysis.DependencyAnalyzerBase+<AnalyzeCore>d__8.MoveNext () [0x0012a] in <f1e806506b924da79745f061b5840ca1>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj]
MSBUILD : error :   at Codartis.NsDepCop.MsBuildTask.NsDepCopTask.Execute () [0x00123] in <163db0d5886241208b2b198d0a6c8372>:0  [/Users/d/_DEVOPS_Agent/_work/1/s/NCC/NameOfProject.NetStandard.csproj] ```
